name: Execute Precise Booking
on:
  schedule:
    # Runs at 8:30 AM Vietnam Time (1:30 AM UTC)
    - cron: '30 1 * * *'

concurrency:
  group: booking-execution
  cancel-in-progress: false

jobs:
  run-booking-script:
    runs-on: ubuntu-latest
    steps:
      - name: Download the execution package
        uses: actions/download-artifact@v4
        with:
          name: booking-package

      - name: Execute the booking script
        env:
          VINHOMES_TOKEN_REFERENCE: ${{ secrets.VINHOMES_TOKEN_REFERENCE }}
          PYTHONPATH: ./dependencies
        run: python book_tennis.py
