name: Prepare Booking Script
on:
  schedule:
    # Runs at 8:28 AM Vietnam Time (1:28 AM UTC)
    - cron: '28 1 * * *'

jobs:
  prepare-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies into a folder
        run: pip install --target=./dependencies -r requirements.txt

      - name: Create execution package (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: booking-package
          path: |
            scripts/book_tennis.py
            dependencies
